**Luis Angel Garcia Montiel**

**Ingenieria en computacion** 

**Graficacion Computacional**

**Hazem Alvarez**

**Matrices**


**11 de Noviembre del 2024**

**Sistemas de ecuaciones lineales con numpy**


Python permite resolver fácilmente sistemas de ecuaciones lineales empleando  **numpy** 


*Un sistema de n ecuaciones con n incógnitas se puede escribir de la siguiente forma:*


*También se puede escribir en forma matricial*


*Esto se puede reescribir de forma compacta utilizando Ax=b, donde A es una matriz de dimensión nxn y x y b son dos vectores columna de longitud n.*

*Recuperado de Sistemas de ecuaciones lineales con numpy en https://www.analyticslane.com/2018/10/29/sistemas-de-ecuaciones-lineales-con-numpy/*

In [6]:
import numpy as np

# Definir las matrices
A = np.matrix([[2, 3], [1, -2]])
b = np.matrix([[8], [-10]])


    print("Matriz A:")
    print(A)
    print("\nMatriz b:")
    print(b)
    print("\nSolución x:")
    print(x)


Matriz A:
[[ 2  3]
 [ 1 -2]]

Matriz b:
[[  8]
 [-10]]

Solución x:
[[-2.]
 [ 4.]]


In [13]:
print(np.linalg.det(A))

-7.000000000000001


*Empleando la ecuación **Ax=b** se despeja **x** y se asume que la matriz **A** es regular, se puede multiplicar la expresión por la inversa de **A**, **A-1**

*Por tanto **A-1A** es la matriz identidad y se puede escribir la solución del sistema como:

In [7]:
x = (A**-1)*b
print ("Inverse A-1 /n", x)

Inverse A-1 /n [[-2.]
 [ 4.]]


In [9]:
import numpy as np

A4 = np.matrix([[3, 2, -1], [2, -2, 4], [-1, 1/2, -1]])
b4 = np.matrix([[1], [-2], [0]])

print('This is A\n', A4)
print('This is b\n', b4)


This is A
 [[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]
This is b
 [[ 1]
 [-2]
 [ 0]]


In [11]:
x = (A4**-1)*b4
print (x)

[[ 1.]
 [-2.]
 [-2.]]


In [14]:
print(np.linalg.det(A4))

-3.0000000000000018


**EJERCICIO**

In [19]:
import numpy as np

# Definición de la matriz B

B = np.array([[4, -1], [-2, 0]])
print("Matriz B:")
print(B)

# Cálculo del determinante de B

determinante_B = np.linalg.det(B)
print("Determinante de B:", determinante_B)

# Verificación de invertibilidad y cálculo de solución

if determinante_B != 0:
    
    # Definimos un vector b para el sistema Bx = b
    
    b_vector = np.array([1, 0])  # Añadimos cualquier vector 
    solucion_B = np.linalg.solve(B, b_vector)
    print("Solución de Bx = b:", solucion_B)
else:
    print("La matriz B no es invertible, por lo tanto, no tiene solución única.")



Matriz B:
[[ 4 -1]
 [-2  0]]
Determinante de B: -2.0
Solución de Bx = b: [ 0. -1.]


In [20]:
# Definición de la matriz C

C = np.array([[5, 0, 2], [3, 1, 1], [0, 1, 2]])
print("Matriz C:")
print(C)

# Cálculo del determinante de C

determinante_C = np.linalg.det(C)
print("Determinante de C:", determinante_C)

# Verificación de invertibilidad y cálculo de solución

if determinante_C != 0:
    
    # Definimos un vector b para el sistema Cx = b
    
    b_vector = np.array([1, 1, 1])  # Cambia este vector según sea necesario
    solucion_C = np.linalg.solve(C, b_vector)
    print("Solución de Cx = b:", solucion_C)
else:
    print("La matriz C no es invertible, por lo tanto, no tiene solución única.")



Matriz C:
[[5 0 2]
 [3 1 1]
 [0 1 2]]
Determinante de C: 11.000000000000002
Solución de Cx = b: [0.09090909 0.45454545 0.27272727]


In [22]:
import numpy as np

# Ejemplo de la matriz B

B = np.array([[4, -1], [-2, 0]])
determinante_B = np.linalg.det(B)
print("Determinante de B:", determinante_B)

# Representación matricial del sistema

A = np.array([[3, 2, -1], [2, -2, 4], [-1, 0.5, -1]])
b = np.array([1, -2, 0])

# Resolución del sistema

x = np.linalg.solve(A, b)
print("Solución del sistema:", x)

# Determinante de la matriz A

determinante_A = np.linalg.det(A)
print("Determinante de A:", determinante_A)

Determinante de B: -2.0
Solución del sistema: [ 1. -2. -2.]
Determinante de A: -3.0000000000000018
